export * from './duck'
export * from './mallard_duck'
export * from './rubber_duck'
export * from './flyWithWings'
export * from './quack'
export * from './flyBehavior'
export * from './quackBehavior'
